version: '3'

services:
  app:
    build: .
    container_name: app
    entrypoint: wait-for database:3306 -t 40 -- npm run start
    depends_on:
      - database
      - nginx
    volumes:
      - ./:/usr/src/app
    networks:
      - node-network

  database:
    image: mysql:8.0.33
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: sample
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - node-network

  nginx:
    image: nginx:1.23.1-alpine
    container_name: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    networks: 
      - node-network
    
networks:
  node-network:
    driver: bridge